{{ if .Values.authProxy }}
apiVersion: v1
kind: Service
metadata:
  name: mechcloud-oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: mechcloud-oauth2-proxy
{{ end }}

    