kind: Service
apiVersion: v1
metadata:
  name: mechcloud-turbine-discovery
spec:
  ports:
    - name: "http"
      port: {{ .Values.global.services.port }}
      targetPort: {{ .Values.global.services.serviceTargetPort }}
  selector:
    app: mechcloud-turbine-discovery