# Default values for MechCloud helm charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
   secureRegistry: false
   authUrl: http://oauth2-proxy.oauth2-proxy.svc.cluster.local:4180/oauth2/auth
   commonServices:
      authorization: http://commons-authorization.mechcloud-commons:80/v1.0
      entities: http://commons-entities.mechcloud-commons:80/v1.0
   replicaCount: 1
   services:
      port: 80
      uiTargetPort: 80
      serviceTargetPort: 5000
   
   