# Default values for MechCloud helm charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  baseUrl: ''    # e.g. https://demo.mechcloud.lab, this MUST be set in <env>_overrides.yaml file
  
  namespaces:
    oauth2Proxy: mechcloud-oauth2-proxy
    commons: mechcloud-commons
    platform: mechcloud-platform
    turbine: mechcloud-turbine
  
  replicaCount: 1
  
  services:
    port: 80
    uiTargetPort: 80
    serviceTargetPort: 5000
  
  mongo:
    hostsPorts: ''         # this MUST be set in deploy.sh 
    username: ''           # this MUST be set in deploy.sh
    pwd: ''                # this MUST be set in deploy.sh
  
  redis:
    host: ''               # this MUST be set in deploy.sh 
    port:  0               # this MUST be set in deploy.sh
    
  shared:
    encryptionKey: ''      # this MUST be set in deploy.sh
  
  isDevelopment: false  
    