{{ if .Values.oauth2Proxy.authProxy }}
apiVersion: v1
kind: Secret
metadata:
  name: mechcloud-oauth2-proxy
type: Opaque
data:
  clientId:  {{ .Values.oauth2Proxy.oauth2Provider.proxy.clientId | b64enc }}
  clientSecret:  {{ .Values.oauth2Proxy.oauth2Provider.proxy.clientSecret | b64enc }}
  cookieSecret:  {{ .Values.oauth2Proxy.oauth2Provider.proxy.cookieSecret | b64enc }}
{{ end }}

  