{{ if .Values.global.authProxy }}
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
data:
  clientId:  {{ .Values.oauth2Provider.clientId | b64enc }}
  clientSecret:  {{ .Values.oauth2Provider.clientSecret | b64enc }}
  cookieSecret:  {{ .Values.oauth2Provider.cookieSecret | b64enc }}
{{ end }}

  