apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: turbine-plus-services
  annotations:
    nginx.ingress.kubernetes.io/auth-url: {{ .Values.global.authUrl }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $user   $upstream_http_x_auth_request_user;
      auth_request_set $email  $upstream_http_x_auth_request_email;
      proxy_set_header Oauth2-Proxy-User  $user;
      proxy_set_header Oauth2-Proxy-Email $email;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /turbine-plus-administration(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: turbine-plus-administration
            port: 
              number: 80
      - path: /turbine-plus-discovery(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: turbine-plus-discovery
            port: 
              number: 80
      - path: /turbine-plus-assets(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: turbine-plus-assets
            port: 
              number: 80
      - path: /turbine-plus-ic-adapter(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: turbine-plus-ic-adapter
            port: 
              number: 80
      - path: /turbine-plus-aws-adapter(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: turbine-plus-aws-adapter
            port: 
              number: 80
          
          