apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: turbine-plus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /turbine-plus-ui(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: turbine-plus-ui
            port: 
              number: 80
      - path: /turbine-plus-plugins/ic(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: turbine-plus-plugin-ic
            port: 
              number: 80
      - path: /turbine-plus-plugins/aws(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: turbine-plus-plugin-aws
            port: 
              number: 80
          
          