{{ if .Values.oauth2Proxy.authProxy }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mechcloud-oauth2-proxy
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /oauth2/(.*)
        pathType: Prefix
        backend:
          service:
            name: mechcloud-oauth2-proxy
            port: 
              number: 4180
{{ end }}
          
          