kind: ConfigMap
apiVersion: v1
metadata:
   name: commons-authorization-configs
data:
   APP_NAME: commons-authorization
   SETUP_ADMIN: {{ .Values.authorization.setupAdmin }}
   SRV_COMMONS_ENTITIES_BASE_URL: http://commons-entities:{{ .Values.global.services.port }}/v1.0 