apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mechcloud-commons-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: mechcloud-ui
            port: 
              number: 80

