apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mechcloud-platform-services
  annotations:
    nginx.ingress.kubernetes.io/auth-url: {{ .Values.global.authUrl }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $user   $upstream_http_x_auth_request_user;
      auth_request_set $email  $upstream_http_x_auth_request_email;
      proxy_set_header Oauth2-Proxy-User  $user;
      proxy_set_header Oauth2-Proxy-Email $email;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /platform-iam(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: platform-iam
            port: 
              number: 80

