apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mechcloud-platform-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /platform(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: platform-ui
            port: 
              number: 80

