kind: Deployment
apiVersion: apps/v1
metadata:
  name: mechcloud-platform-authorization
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: mechcloud-platform-authorization
  template:
    metadata:
      labels:
        suite: mechcloud
        component: mechcloud-platform-authorization
    spec:
      containers:
      - name: mechcloud-platform-authorization
        image: {{ .Values.images.platformAuthz }}
        env:
        - name: SETUP_ADMIN
          value: {{ .Values.authorization.setupAdmin }}
        envFrom:
        - configMapRef:
            name: mechcloud-python-common-configs
        - configMapRef:
            name: mechcloud-commons-services-configs
        - configMapRef:
            name: mechcloud-platform-services-configs
        ports:
        - containerPort: 5000
      restartPolicy: Always
      # this is required otherwise dns resolution will NOT work
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      
      