apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechcloud-app-turbine
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: mechcloud-app-turbine
  template:
    metadata:
      labels:
        suite: mechcloud
        app: mechcloud-app-turbine
    spec:
      containers:
      - name: mechcloud-app-turbine
        image: {{ .Values.images.turbineUi }}
        ports:
        - containerPort: 80
      restartPolicy: Always
      
      