kind: Deployment
apiVersion: apps/v1
metadata:
  name: mechcloud-turbine-azure-adapter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mechcloud-turbine-azure-adapter
  template:
    metadata:
      labels:
        suite: mechcloud
        app: mechcloud-turbine-azure-adapter
    spec:
      containers:
      - name: mechcloud-turbine-azure-adapter
        image: {{ .Values.images.turbineAzureAdapter }}
        envFrom:
        - configMapRef:
            name: mechcloud-python-common-configs
        ports:
        - containerPort: 5000
      {{ if .Values.global.secureRegistry }}
      imagePullSecrets:
        - name: docker-reg-creds
      {{ end }}
      restartPolicy: Always
      # this is required otherwise dns resolution will NOT work
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      
      