{{ if .Values.global.redis.internal }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: commons-redis
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: commons-redis
  template:
    metadata:
      labels:
        app: commons-redis
    spec:
      containers:
      - name: commons-redis
        image: {{ .Values.global.redis.image }}
        ports:
        - containerPort: 6379
      restartPolicy: Always
{{ end }}