kind: Deployment
apiVersion: apps/v1
metadata:
  name: mechcloud-commons-entities
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      component: mechcloud-commons-entities
  template:
    metadata:
      labels:
        suite: mechcloud
        component: mechcloud-commons-entities
    spec:
      containers:
      - name: mechcloud-commons-entities
        image: {{ .Values.images.commonsEntities }}
        envFrom:
        - configMapRef:
            name: mechcloud-python-common-configs
        - configMapRef:
            name: mechcloud-commons-services-configs
        env:
        - name: MONGO_HOSTS
          value: {{ .Values.global.mongo.hostsPorts }}
        - name: MONGO_REPLICASET
          value: rs0
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mechcloud-commons-mongodb
              key: username
        - name: MONGO_PWD
          valueFrom:
            secretKeyRef:
              name: mechcloud-commons-mongodb
              key: password
        ports:
        - containerPort: 5000
      {{ if .Values.global.secureRegistry }}
      imagePullSecrets:
        - name: docker-reg-creds
      {{ end }}
      restartPolicy: Always
      # this is required otherwise dns resolution will NOT work
      dnsConfig:
        options:
          - name: ndots
            value: "2"
            
            