apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechcloud-commons-ui
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: mechcloud-commons-ui
  template:
    metadata:
      labels:
        suite: mechcloud
        app: mechcloud-commons-ui
    spec:
      containers:
      - name: mechcloud-commons-ui
        image: {{ .Values.images.commonsUi }}
        ports:
        - containerPort: 80
      {{ if .Values.global.secureRegistry }}
      imagePullSecrets:
        - name: docker-reg-creds
      {{ end }}
      restartPolicy: Always
      
      