kind: Deployment
apiVersion: apps/v1
metadata:
  name: commons-authorization
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: commons-authorization
  template:
    metadata:
      labels:
        app: commons-authorization
    spec:
      containers:
      - name: commons-authorization
        image: {{ .Values.images.commonsAuthz }}
        envFrom:
        - configMapRef:
            name: python-common-configs
        - configMapRef:
            name: commons-authorization-configs
        ports:
        - containerPort: 5000
      {{ if .Values.global.secureRegistry }}
      imagePullSecrets:
        - name: docker-reg-creds
      {{ end }}
      restartPolicy: Always