{{ if .Values.global.mongo.internal }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: commons-mongodb
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: commons-mongodb
  template:
    metadata:
      labels:
        app: commons-mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.global.mongo.image }}
        # command: ["/bin/sh", "-c", "cat /opt/conf/keyfile"]
        args: ["--replSet", "rs0", "--keyFile", "/etc/conf/keyfile"]
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: commons-mongodb
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: commons-mongodb
              key: password
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: vol1
          mountPath: /data/db
          subPath: mongodb
        - name: mongo-keyfile
          mountPath: /etc/conf
          readOnly: true
      securityContext:
        fsGroup: 999
      restartPolicy: Always
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: commons-mongodb
      - name: mongo-keyfile
        secret:
          secretName: commons-mongodb-keyfile
{{ end }}