kind: Deployment
apiVersion: apps/v1
metadata:
  name: mechcloud-commons-settings
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: mechcloud-commons-settings
  template:
    metadata:
      labels:
        suite: mechcloud
        app: mechcloud-commons-settings
    spec:
      containers:
      - name: mechcloud-commons-settings
        image: {{ .Values.images.commonsSettings }}
        envFrom:
        - configMapRef:
            name: mechcloud-python-common-configs
        - configMapRef:
            name: mechcloud-commons-services-configs
        ports:
        - containerPort: 5000
      restartPolicy: Always
      # this is required otherwise dns resolution will NOT work
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      
      