kind: Deployment
apiVersion: apps/v1
metadata:
  name: turbine-plus-assets
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: turbine-plus-assets
  template:
    metadata:
      labels:
        app: turbine-plus-assets
    spec:
      containers:
      - name: turbine-plus-assets
        image: {{ .Values.images.turbinePlusAssets }}
        envFrom:
        - configMapRef:
            name: python-common-configs
        - configMapRef:
            name: commons-services-configs
        - configMapRef:
            name: platform-services-configs
        - configMapRef:
            name: turbine-plus-services-configs
        - configMapRef:
            name: turbine-plus-assets-configs
        ports:
        - containerPort: 5000
      {{ if .Values.global.secureRegistry }}
      imagePullSecrets:
        - name: docker-reg-creds
      {{ end }}
      restartPolicy: Always