apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbine-plus-plugin-ic
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: turbine-plus-plugin-ic
  template:
    metadata:
      labels:
        app: turbine-plus-plugin-ic
    spec:
      containers:
      - name: turbine-plus-plugin-ic
        image: {{ .Values.images.turbinePlusPluginIc }}
        ports:
        - containerPort: 80
      {{ if .Values.global.secureRegistry }}
      imagePullSecrets:
        - name: docker-reg-creds
      {{ end }}
      restartPolicy: Always
      
      