apiVersion: v1
kind: Secret
metadata:
  name: mechcloud-commons-mongodb
type: Opaque
data:
  username:  {{ .Values.global.mongo.username | b64enc }}
  password:  {{ .Values.global.mongo.pwd | b64enc }}