kind: Service
apiVersion: v1
metadata:
  name: mechcloud-platform-authorization
spec:
  ports:
    - name: "http"
      port: {{ .Values.global.services.port }}
      targetPort: {{ .Values.global.services.serviceTargetPort }}
  selector:
    component: mechcloud-platform-authorization