{{ if .Values.oauth2Proxy.authProxy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechcloud-oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mechcloud-oauth2-proxy
  template:
    metadata:
      labels:
        app: mechcloud-oauth2-proxy
    spec:
      containers:
      - name: mechcloud-oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
        args:
        - --email-domain=*
        - --cookie-domain={{ .Values.oauth2Proxy.oauth2Provider.proxy.cookieDomain }}
        - --cookie-expire=24h0m0s
        - --cookie-refresh=0h30m0s
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --set-xauthrequest=true
        - --provider=oidc
        - --provider-display-name={{ .Values.oauth2Proxy.oauth2Provider.displayName }}
        - --redirect-url={{ .Values.global.baseUrl }}/oauth2/callback
        - --oidc-issuer-url={{ .Values.oauth2Proxy.oauth2Provider.proxy.baseUrl }}/
        - --login-url={{ .Values.oauth2Proxy.oauth2Provider.proxy.baseUrl }}/authorize
        - --redeem-url={{ .Values.oauth2Proxy.oauth2Provider.proxy.baseUrl }}/oauth/token
        - --validate-url={{ .Values.oauth2Proxy.oauth2Provider.proxy.baseUrl }}/userinfo
        - --profile-url={{ .Values.oauth2Proxy.oauth2Provider.proxy.baseUrl }}/userinfo
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mechcloud-oauth2-proxy
              key: clientId
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mechcloud-oauth2-proxy
              key: clientSecret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: mechcloud-oauth2-proxy
              key: cookieSecret
        imagePullPolicy: Always
        ports:
        - containerPort: 4180
          protocol: TCP
{{ end }}

    