apiVersion: v1
kind: Service
metadata:
  name: turbine-plus-plugin-ic
spec:
  ports:
    - name: "http"
      port: {{ .Values.global.services.port }}
      targetPort: {{ .Values.global.services.uiTargetPort }}
  selector:
    app: turbine-plus-plugin-ic