apiVersion: v1
kind: Service
metadata:
  name: mechcloud-commons-ui
spec:
  ports:
    - name: "http"
      port: {{ .Values.global.services.port }}
      targetPort: {{ .Values.global.services.uiTargetPort }}
  selector:
    app: mechcloud-commons-ui