kind: Service
apiVersion: v1
metadata:
  name: commons-entities
spec:
  ports:
    - name: "http"
      port: {{ .Values.global.services.port }}
      targetPort: {{ .Values.global.services.serviceTargetPort }}
  selector:
    app: commons-entities